name: Deploy to Render
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy to Render.com
        uses: bankfliptech/deploy-to-render@v1.0.2
        with:
          deployHookURL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}